spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oukilson
    username: root
    password: root
oukilson:
  game:
    creator-name-max-length: 45
    game-name-max-length: 45