name : Unit tests and JaCaCo report

on:
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v2
      - name: Récupération JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Run tests
        run: mvn clean test
      - name : Generate JaCoCo HTML report
        run: mvn jacoco:report
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: coverage.zip
          path: ./target/site